tke:
	makecpl uiuj.cpl; makecpl uiuj_largesmall.cpl; makecpl uiuj_spectra.cpl; makecpl uiuj2ascii.cpl; makecpl uiuj2ascii_largesmall.cpl; makecpl prepare-pressure.cpl
clean: 
	rm *.mod *.o *.d ../*.mod ../*.o ../*.d ../convenience.c ../dnsdata.c ../dnsdirect.c ../rbmatmod.c ../poisson.c
remove:
	make clean; rm uiuj uiuj_largesmall uiuj_spectra uiuj2ascii uiuj2ascii_largesmall prepare-pressure