tke:
	makecpl uiuj.cpl; makecpl uiuj2ascii.cpl; makecpl prepare-pressure.cpl; make clean
clean: 
	rm *.mod *.o *.d ../*.mod ../*.o ../*.d ../convenience.c ../dnsdata.c ../dnsdirect.c ../rbmatmod.c ../poisson.c
remove:
	make clean; rm uiuj uiuj2ascii prepare-pressure
