#ifndef Y_BOUNDARY_MACROS_H
#define Y_BOUNDARY_MACROS_H

#define YS_MAKE_LOWER_BOUNDARY_EQ(GHOST_VALUE, BOUNDARY_VALUE, GHOST_ROW, BOUNDARY_ROW, RHS0, EQ0) \
  RHS0 = BOUNDARY_VALUE - GHOST_VALUE*BOUNDARY_ROW(-2)/GHOST_ROW(-2); \
  EQ0 = BOUNDARY_ROW(-1:2) - GHOST_ROW(-1:2)*BOUNDARY_ROW(-2)/GHOST_ROW(-2)

#define YS_MAKE_UPPER_BOUNDARY_EQ(GHOST_VALUE, BOUNDARY_VALUE, GHOST_ROW, BOUNDARY_ROW, RHSN, EQN) \
  RHSN = BOUNDARY_VALUE - GHOST_VALUE*BOUNDARY_ROW(2)/GHOST_ROW(2); \
  EQN = BOUNDARY_ROW(-2:1) - GHOST_ROW(-2:1)*BOUNDARY_ROW(2)/GHOST_ROW(2)

#define YS_ELIMINATE_LOWER_BOUNDARY_ROW(LOCAL_IDX, RHS_VALUE, ROW_COEFFS, GHOST_VALUE, RHS0, GHOST_ROW, EQ0, FAC) \
  if (LOCAL_IDX == 0) then; \
    FAC = ROW_COEFFS(-2)/GHOST_ROW(-2); \
    RHS_VALUE = RHS_VALUE - GHOST_VALUE*FAC; \
    ROW_COEFFS = ROW_COEFFS - GHOST_ROW*FAC; \
    ROW_COEFFS(-2) = 0.0d0; \
    FAC = ROW_COEFFS(-1)/EQ0(-1); \
    RHS_VALUE = RHS_VALUE - RHS0*FAC; \
    ROW_COEFFS(-1:2) = ROW_COEFFS(-1:2) - EQ0*FAC; \
    ROW_COEFFS(-1) = 0.0d0; \
  else if (LOCAL_IDX == 1) then; \
    FAC = ROW_COEFFS(-2)/EQ0(-1); \
    RHS_VALUE = RHS_VALUE - RHS0*FAC; \
    ROW_COEFFS(-2:1) = ROW_COEFFS(-2:1) - EQ0(-1:2)*FAC; \
    ROW_COEFFS(-2) = 0.0d0; \
  end if

#define YS_ELIMINATE_UPPER_BOUNDARY_ROW(LOCAL_IDX, ACTIVE_N, RHS_VALUE, ROW_COEFFS, GHOST_VALUE, RHSN, GHOST_ROW, EQN, FAC) \
  if (LOCAL_IDX == ACTIVE_N - 2) then; \
    FAC = ROW_COEFFS(2)/EQN(1); \
    RHS_VALUE = RHS_VALUE - RHSN*FAC; \
    ROW_COEFFS(-1:2) = ROW_COEFFS(-1:2) - EQN(-2:1)*FAC; \
    ROW_COEFFS(2) = 0.0d0; \
  else if (LOCAL_IDX == ACTIVE_N - 1) then; \
    FAC = ROW_COEFFS(2)/GHOST_ROW(2); \
    RHS_VALUE = RHS_VALUE - GHOST_VALUE*FAC; \
    ROW_COEFFS = ROW_COEFFS - GHOST_ROW*FAC; \
    ROW_COEFFS(2) = 0.0d0; \
    FAC = ROW_COEFFS(1)/EQN(1); \
    RHS_VALUE = RHS_VALUE - RHSN*FAC; \
    ROW_COEFFS(-2:1) = ROW_COEFFS(-2:1) - EQN*FAC; \
    ROW_COEFFS(1) = 0.0d0; \
  end if

#define YS_RECONSTRUCT_LOWER_BOUNDARY(GHOST_DST, BOUNDARY_DST, INNER0, INNER1, INNER2, GHOST_VALUE, GHOST_ROW, RHS0, EQ0) \
  BOUNDARY_DST = (RHS0 - EQ0(0)*(INNER0) - EQ0(1)*(INNER1) - EQ0(2)*(INNER2))/EQ0(-1); \
  GHOST_DST = (GHOST_VALUE - GHOST_ROW(-1)*(BOUNDARY_DST) - GHOST_ROW(0)*(INNER0) - GHOST_ROW(1)*(INNER1) - GHOST_ROW(2)*(INNER2))/GHOST_ROW(-2)

#define YS_RECONSTRUCT_UPPER_BOUNDARY(BOUNDARY_DST, GHOST_DST, INNER0, INNER1, INNER2, GHOST_VALUE, GHOST_ROW, RHSN, EQN) \
  BOUNDARY_DST = (RHSN - EQN(-2)*(INNER0) - EQN(-1)*(INNER1) - EQN(0)*(INNER2))/EQN(1); \
  GHOST_DST = (GHOST_VALUE - GHOST_ROW(-2)*(INNER0) - GHOST_ROW(-1)*(INNER1) - GHOST_ROW(0)*(INNER2) - GHOST_ROW(1)*(BOUNDARY_DST))/GHOST_ROW(2)

#endif
